package com.github.micycle1.robustpredicates.codegen;

import com.github.micycle1.robustpredicates.errorbound.ErrorBoundDeriver;
import com.github.micycle1.robustpredicates.expansion.ExpansionEvaluator;
import com.github.micycle1.robustpredicates.expr.EvaluationPlan;
import com.github.micycle1.robustpredicates.expr.Expression;
import com.github.micycle1.robustpredicates.expr.Expressions;
import com.github.micycle1.robustpredicates.expr.Op;
import com.github.micycle1.robustpredicates.expr.PredicateSpec;

import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;

/**
 * Emits flat, adaptive robust predicate routines as Java source.
 *
 * <p>For every {@link PredicateSpec} three straight-line stage methods are
 * generated from the same construction-time plans that the interpreted stages
 * use, so generated and interpreted results agree bit for bit:
 * <ul>
 *   <li><b>stage A</b> — the semi-static filter: one local per plan slot,
 *       derived error-bound constants baked in as hex double literals, fully
 *       self-contained;</li>
 *   <li><b>stage B</b> — exact-difference tail checks with early
 *       {@code SIGN_UNCERTAIN} returns, then reduced-size expansion evaluation
 *       via {@code ExpansionArithmetic};</li>
 *   <li><b>stage D</b> — full expansion evaluation, always exact;</li>
 * </ul>
 * plus a public driver that chains them.
 *
 * <p>Output is deterministic: plan ordering follows the expression build
 * order and doubles are always formatted as hex literals
 * ({@link Double#toHexString}), never decimal.
 */
public final class CodeGenerator {

    private CodeGenerator() {
    }

    /** The canonical generated source for the standard predicates. */
    public static String generateDefault() {
        return generateClass("com.github.micycle1.robustpredicates", "RobustPredicates",
                Expressions.SPECS);
    }

    public static String generateClass(String packageName, String className,
                                       List<PredicateSpec> specs) {
        StringBuilder sb = new StringBuilder();
        sb.append("// GENERATED FILE - DO NOT EDIT.\n");
        sb.append("// Generated by the robust-predicates-framework code generator from the\n");
        sb.append("// predicate definitions in Expressions. Regenerate with:\n");
        sb.append("//   mvn -Pcodegen -pl framework -am process-classes\n");
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("/**\n");
        sb.append(" * Adaptive exact geometric predicates: each public method runs a fast\n");
        sb.append(" * floating-point filter with a derived error bound (stage A), an\n");
        sb.append(" * exact-difference expansion stage (stage B) and an exact\n");
        sb.append(" * expansion-arithmetic fallback (stage D), so the returned sign is always\n");
        sb.append(" * the exact sign of the predicate, provided no intermediate product over-\n");
        sb.append(" * or underflows (the same domain restriction as Shewchuk's original\n");
        sb.append(" * routines).\n");
        sb.append(" *\n");
        sb.append(" * <p>The documented 2D conventions assume the usual mathematical\n");
        sb.append(" * orientation with the y axis pointing up; with a downward y axis (screen\n");
        sb.append(" * coordinates) the geometric reading of the signs flips (counterclockwise\n");
        sb.append(" * reads as clockwise, left as right).\n");
        sb.append(" */\n");
        sb.append("public final class ").append(className).append(" {\n\n");
        sb.append("    /** Internal sentinel: a filter stage could not certify the sign. */\n");
        sb.append("    public static final int SIGN_UNCERTAIN = -2;\n\n");
        sb.append("    private ").append(className).append("() {\n    }\n");
        for (PredicateSpec spec : specs) {
            emitDriver(sb, spec);
            emitStageA(sb, spec);
            emitExpansionStage(sb, spec, true);
            emitExpansionStage(sb, spec, false);
        }
        sb.append("}\n");
        return sb.toString();
    }

    // ------------------------------------------------------------------
    // Driver
    // ------------------------------------------------------------------

    private static void emitDriver(StringBuilder sb, PredicateSpec spec) {
        String params = String.join(", ",
                spec.params().stream().map(p -> "double " + p).toList());
        String args = String.join(", ", spec.params());
        sb.append('\n');
        sb.append("    /** ").append(spec.javadoc()).append(" */\n");
        sb.append("    public static int ").append(spec.name()).append('(').append(params)
                .append(") {\n");
        sb.append("        int s = ").append(spec.name()).append("StageA(").append(args)
                .append(");\n");
        sb.append("        if (s != SIGN_UNCERTAIN) {\n            return s;\n        }\n");
        sb.append("        s = ").append(spec.name()).append("StageB(").append(args)
                .append(");\n");
        sb.append("        if (s != SIGN_UNCERTAIN) {\n            return s;\n        }\n");
        sb.append("        return ").append(spec.name()).append("StageD(").append(args)
                .append(");\n");
        sb.append("    }\n");
    }

    // ------------------------------------------------------------------
    // Stage A
    // ------------------------------------------------------------------

    private static void emitStageA(StringBuilder sb, PredicateSpec spec) {
        Expression det = spec.expression();
        Expression err = new ErrorBoundDeriver().deriveErrorExpression(det);
        EvaluationPlan plan = EvaluationPlan.of(det, err);
        String params = String.join(", ",
                spec.params().stream().map(p -> "double " + p).toList());
        sb.append('\n');
        sb.append("    static int ").append(spec.name()).append("StageA(").append(params)
                .append(") {\n");
        List<Expression> nodes = plan.nodes();
        for (int i = 0; i < nodes.size(); i++) {
            Expression node = nodes.get(i);
            if (node.isLeaf()) {
                continue;
            }
            sb.append("        final double v").append(i).append(" = ")
                    .append(scalarExpr(node, plan, spec)).append(";\n");
        }
        String detRef = "v" + plan.rootSlot(0);
        String errRef = "v" + plan.rootSlot(1);
        sb.append("        if (").append(detRef).append(" > ").append(errRef)
                .append(") {\n            return 1;\n        }\n");
        sb.append("        if (").append(detRef).append(" < -").append(errRef)
                .append(") {\n            return -1;\n        }\n");
        sb.append("        if (").append(errRef).append(" == 0.0 && ").append(detRef)
                .append(" == 0.0) {\n            return 0;\n        }\n");
        sb.append("        return SIGN_UNCERTAIN;\n");
        sb.append("    }\n");
    }

    private static String scalarExpr(Expression node, EvaluationPlan plan, PredicateSpec spec) {
        return switch (node.op()) {
            case ABS -> "Math.abs(" + scalarRef(node.left(), plan, spec) + ")";
            case SUM -> scalarRef(node.left(), plan, spec) + " + "
                    + scalarRef(node.right(), plan, spec);
            case DIFFERENCE -> scalarRef(node.left(), plan, spec) + " - "
                    + scalarRef(node.right(), plan, spec);
            case PRODUCT -> scalarRef(node.left(), plan, spec) + " * "
                    + scalarRef(node.right(), plan, spec);
            case MAX -> "Math.max(" + scalarRef(node.left(), plan, spec) + ", "
                    + scalarRef(node.right(), plan, spec) + ")";
            case MIN -> "Math.min(" + scalarRef(node.left(), plan, spec) + ", "
                    + scalarRef(node.right(), plan, spec) + ")";
            default -> throw new IllegalArgumentException("leaf has no expression: " + node);
        };
    }

    private static String scalarRef(Expression node, EvaluationPlan plan, PredicateSpec spec) {
        return switch (node.op()) {
            case ARGUMENT -> spec.params().get(node.argN() - 1);
            case CONSTANT -> hexLiteral(node.value());
            default -> "v" + plan.slotOf(node);
        };
    }

    private static String hexLiteral(double v) {
        return Double.toHexString(v);
    }

    // ------------------------------------------------------------------
    // Stages B and D
    // ------------------------------------------------------------------

    private static void emitExpansionStage(StringBuilder sb, PredicateSpec spec,
                                           boolean stageB) {
        ExpansionEvaluator.Plan plan =
                new ExpansionEvaluator(spec.expression(), stageB).plan();
        Map<Expression, Integer> index = new IdentityHashMap<>();
        for (int i = 0; i < plan.evals().size(); i++) {
            index.put(plan.evals().get(i), i);
        }
        String params = String.join(", ",
                spec.params().stream().map(p -> "double " + p).toList());
        sb.append('\n');
        sb.append("    static int ").append(spec.name()).append(stageB ? "StageB(" : "StageD(")
                .append(params).append(") {\n");
        sb.append("        final double[] buf = new double[").append(plan.totalSize())
                .append("];\n");

        if (stageB) {
            for (int i = 0; i < plan.evals().size(); i++) {
                if (!plan.leafDiff()[i]) {
                    continue;
                }
                Expression node = plan.evals().get(i);
                String l = leafRef(node.left(), spec);
                String r = leafRef(node.right(), spec);
                sb.append("        final double d").append(i).append(" = ").append(l)
                        .append(" - ").append(r).append(";\n");
                sb.append("        if (ExpansionArithmetic.twoDiffTail(").append(l)
                        .append(", ").append(r).append(", d").append(i)
                        .append(") != 0.0) {\n            return SIGN_UNCERTAIN;\n        }\n");
                sb.append("        buf[").append(plan.starts()[i]).append("] = d").append(i)
                        .append(";\n");
            }
        }

        for (int i = 0; i < plan.evals().size(); i++) {
            if (stageB && plan.leafDiff()[i]) {
                continue;
            }
            Expression node = plan.evals().get(i);
            sb.append("        final int e").append(i).append(" = ")
                    .append(expansionCall(node, i, plan, index, spec, stageB))
                    .append(";\n");
        }
        sb.append("        return ExpansionArithmetic.signOf(buf, ")
                .append(plan.starts()[plan.rootIndex()]).append(", e")
                .append(plan.rootIndex()).append(");\n");
        sb.append("    }\n");
    }

    private static String expansionCall(Expression node, int i, ExpansionEvaluator.Plan plan,
                                        Map<Expression, Integer> index, PredicateSpec spec,
                                        boolean stageB) {
        Expression left = node.left();
        Expression right = node.right();
        boolean leftLeaf = left.isLeaf();
        boolean rightLeaf = right.isLeaf();
        String start = String.valueOf(plan.starts()[i]);
        String ze = String.valueOf(plan.ze()[i]);
        switch (node.op()) {
            case SUM, DIFFERENCE -> {
                boolean minus = node.op() == Op.DIFFERENCE;
                if (leftLeaf && rightLeaf) {
                    return "ExpansionArithmetic." + (minus ? "twoDiff" : "twoSum") + "("
                            + leafRef(left, spec) + ", " + leafRef(right, spec)
                            + ", buf, " + start + ", " + ze + ")";
                }
                if (leftLeaf) {
                    return "ExpansionArithmetic.growExpansion(" + range(right, plan, index, stageB)
                            + ", " + leafRef(left, spec) + ", buf, " + start + ", " + minus
                            + ", false, " + ze + ")";
                }
                if (rightLeaf) {
                    return "ExpansionArithmetic.growExpansion(" + range(left, plan, index, stageB)
                            + ", " + leafRef(right, spec) + ", buf, " + start + ", false, "
                            + minus + ", " + ze + ")";
                }
                int li = index.get(left);
                int ri = index.get(right);
                boolean fast = plan.sizes()[li] > 2 && plan.sizes()[ri] > 2;
                return "ExpansionArithmetic." + (fast ? "fastExpansionSum" : "expansionSum") + "("
                        + range(left, plan, index, stageB) + ", "
                        + range(right, plan, index, stageB)
                        + ", buf, " + start + ", false, " + minus + ", " + ze + ")";
            }
            case PRODUCT -> {
                if (leftLeaf && rightLeaf) {
                    return "ExpansionArithmetic.twoProduct(" + leafRef(left, spec) + ", "
                            + leafRef(right, spec) + ", buf, " + start + ", " + ze + ")";
                }
                if (leftLeaf) {
                    return "ExpansionArithmetic.scaleExpansion("
                            + range(right, plan, index, stageB) + ", " + leafRef(left, spec)
                            + ", buf, " + start + ", " + ze + ")";
                }
                if (rightLeaf) {
                    return "ExpansionArithmetic.scaleExpansion("
                            + range(left, plan, index, stageB) + ", " + leafRef(right, spec)
                            + ", buf, " + start + ", " + ze + ")";
                }
                if (left == right && plan.sizes()[index.get(left)] == 2) {
                    return "ExpansionArithmetic.twoSquare(" + range(left, plan, index, stageB)
                            + ", buf, " + start + ", " + ze + ")";
                }
                return "ExpansionArithmetic.expansionTimes(" + range(left, plan, index, stageB)
                        + ", " + range(right, plan, index, stageB) + ", buf, " + start + ", "
                        + ze + ")";
            }
            default -> throw new IllegalArgumentException(
                    "unsupported operator in exact expression: " + node.op());
        }
    }

    /** {@code buf, start, end} triple for a child expansion. */
    private static String range(Expression child, ExpansionEvaluator.Plan plan,
                                Map<Expression, Integer> index, boolean stageB) {
        int ci = index.get(child);
        int start = plan.starts()[ci];
        String end = (stageB && plan.leafDiff()[ci])
                ? String.valueOf(start + 1)
                : "e" + ci;
        return "buf, " + start + ", " + end;
    }

    private static String leafRef(Expression leaf, PredicateSpec spec) {
        return leaf.op() == Op.ARGUMENT
                ? spec.params().get(leaf.argN() - 1)
                : hexLiteral(leaf.value());
    }
}
