// GENERATED FILE - DO NOT EDIT.
// Generated by the robust-predicates-framework code generator from the
// predicate definitions in Expressions. Regenerate with:
//   mvn -Pcodegen -pl framework -am process-classes
package com.github.micycle1.robustpredicates;

/**
 * Adaptive exact geometric predicates: each public method runs a fast
 * floating-point filter with a derived error bound (stage A), an
 * exact-difference expansion stage (stage B) and an exact
 * expansion-arithmetic fallback (stage D), so the returned sign is always
 * the exact sign of the predicate, provided no intermediate product over-
 * or underflows (the same domain restriction as Shewchuk's original
 * routines).
 *
 * <p>The documented 2D conventions assume the usual mathematical
 * orientation with the y axis pointing up; with a downward y axis (screen
 * coordinates) the geometric reading of the signs flips (counterclockwise
 * reads as clockwise, left as right).
 */
public final class RobustPredicates {

    /** Internal sentinel: a filter stage could not certify the sign. */
    public static final int SIGN_UNCERTAIN = -2;

    private RobustPredicates() {
    }

    /** Positive iff {@code c} lies to the left of the directed line {@code a -> b} (counterclockwise {@code abc}, y axis up); zero iff collinear. */
    public static int orient2d(double ax, double ay, double bx, double by, double cx, double cy) {
        int s = orient2dStageA(ax, ay, bx, by, cx, cy);
        if (s != SIGN_UNCERTAIN) {
            return s;
        }
        s = orient2dStageB(ax, ay, bx, by, cx, cy);
        if (s != SIGN_UNCERTAIN) {
            return s;
        }
        return orient2dStageD(ax, ay, bx, by, cx, cy);
    }

    static int orient2dStageA(double ax, double ay, double bx, double by, double cx, double cy) {
        final double v2 = bx - ax;
        final double v5 = cy - ay;
        final double v6 = v2 * v5;
        final double v8 = cx - ax;
        final double v10 = by - ay;
        final double v11 = v8 * v10;
        final double v12 = v6 - v11;
        final double v14 = Math.abs(v6);
        final double v15 = Math.abs(v11);
        final double v16 = v14 + v15;
        final double v18 = v16 + 0x1.0p-1021;
        final double v19 = 0x1.7fffffe95f621p-52 * v18;
        if (v12 > v19) {
            return 1;
        }
        if (v12 < -v19) {
            return -1;
        }
        if (v19 == 0.0 && v12 == 0.0) {
            return 0;
        }
        return SIGN_UNCERTAIN;
    }

    static int orient2dStageB(double ax, double ay, double bx, double by, double cx, double cy) {
        final double[] buf = new double[12];
        final double d0 = bx - ax;
        if (ExpansionArithmetic.twoDiffTail(bx, ax, d0) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[0] = d0;
        final double d1 = cy - ay;
        if (ExpansionArithmetic.twoDiffTail(cy, ay, d1) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[1] = d1;
        final double d3 = cx - ax;
        if (ExpansionArithmetic.twoDiffTail(cx, ax, d3) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[4] = d3;
        final double d4 = by - ay;
        if (ExpansionArithmetic.twoDiffTail(by, ay, d4) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[5] = d4;
        final int e2 = ExpansionArithmetic.expansionTimes(buf, 0, 1, buf, 1, 2, buf, 2, false);
        final int e5 = ExpansionArithmetic.expansionTimes(buf, 4, 5, buf, 5, 6, buf, 6, false);
        final int e6 = ExpansionArithmetic.expansionSum(buf, 2, e2, buf, 6, e5, buf, 8, false, true, false);
        return ExpansionArithmetic.signOf(buf, 8, e6);
    }

    static int orient2dStageD(double ax, double ay, double bx, double by, double cx, double cy) {
        final double[] buf = new double[40];
        final int e0 = ExpansionArithmetic.twoDiff(bx, ax, buf, 0, false);
        final int e1 = ExpansionArithmetic.twoDiff(cy, ay, buf, 2, false);
        final int e2 = ExpansionArithmetic.expansionTimes(buf, 0, e0, buf, 2, e1, buf, 4, false);
        final int e3 = ExpansionArithmetic.twoDiff(cx, ax, buf, 12, false);
        final int e4 = ExpansionArithmetic.twoDiff(by, ay, buf, 14, false);
        final int e5 = ExpansionArithmetic.expansionTimes(buf, 12, e3, buf, 14, e4, buf, 16, false);
        final int e6 = ExpansionArithmetic.fastExpansionSum(buf, 4, e2, buf, 16, e5, buf, 24, false, true, false);
        return ExpansionArithmetic.signOf(buf, 24, e6);
    }

    /** Positive iff {@code d} lies below the plane through {@code a, b, c}, where "below" means {@code a, b, c} appear counterclockwise when viewed from above the plane; zero iff coplanar. */
    public static int orient3d(double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double dx, double dy, double dz) {
        int s = orient3dStageA(ax, ay, az, bx, by, bz, cx, cy, cz, dx, dy, dz);
        if (s != SIGN_UNCERTAIN) {
            return s;
        }
        s = orient3dStageB(ax, ay, az, bx, by, bz, cx, cy, cz, dx, dy, dz);
        if (s != SIGN_UNCERTAIN) {
            return s;
        }
        return orient3dStageD(ax, ay, az, bx, by, bz, cx, cy, cz, dx, dy, dz);
    }

    static int orient3dStageA(double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double dx, double dy, double dz) {
        final double v2 = ax - dx;
        final double v5 = by - dy;
        final double v6 = v2 * v5;
        final double v8 = bx - dx;
        final double v10 = ay - dy;
        final double v11 = v8 * v10;
        final double v12 = v6 - v11;
        final double v15 = cz - dz;
        final double v16 = v12 * v15;
        final double v18 = cy - dy;
        final double v19 = v2 * v18;
        final double v21 = cx - dx;
        final double v22 = v21 * v10;
        final double v23 = v19 - v22;
        final double v25 = bz - dz;
        final double v26 = v23 * v25;
        final double v27 = v16 - v26;
        final double v28 = v8 * v18;
        final double v29 = v21 * v5;
        final double v30 = v28 - v29;
        final double v32 = az - dz;
        final double v33 = v30 * v32;
        final double v34 = v27 + v33;
        final double v36 = Math.abs(v6);
        final double v37 = Math.abs(v11);
        final double v38 = v36 + v37;
        final double v40 = v38 + 0x1.0p-1021;
        final double v41 = Math.abs(v15);
        final double v42 = v40 * v41;
        final double v43 = Math.abs(v19);
        final double v44 = Math.abs(v22);
        final double v45 = v43 + v44;
        final double v46 = v45 + 0x1.0p-1021;
        final double v47 = Math.abs(v25);
        final double v48 = v46 * v47;
        final double v49 = v42 + v48;
        final double v50 = Math.abs(v28);
        final double v51 = Math.abs(v29);
        final double v52 = v50 + v51;
        final double v53 = v52 + 0x1.0p-1021;
        final double v54 = Math.abs(v32);
        final double v55 = v53 * v54;
        final double v56 = v49 + v55;
        final double v58 = v56 + 0x1.8p-1021;
        final double v59 = 0x1.bffffff4afb15p-51 * v58;
        if (v34 > v59) {
            return 1;
        }
        if (v34 < -v59) {
            return -1;
        }
        if (v59 == 0.0 && v34 == 0.0) {
            return 0;
        }
        return SIGN_UNCERTAIN;
    }

    static int orient3dStageB(double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double dx, double dy, double dz) {
        final double[] buf = new double[97];
        final double d0 = ax - dx;
        if (ExpansionArithmetic.twoDiffTail(ax, dx, d0) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[0] = d0;
        final double d1 = by - dy;
        if (ExpansionArithmetic.twoDiffTail(by, dy, d1) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[1] = d1;
        final double d3 = bx - dx;
        if (ExpansionArithmetic.twoDiffTail(bx, dx, d3) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[4] = d3;
        final double d4 = ay - dy;
        if (ExpansionArithmetic.twoDiffTail(ay, dy, d4) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[5] = d4;
        final double d7 = cz - dz;
        if (ExpansionArithmetic.twoDiffTail(cz, dz, d7) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[12] = d7;
        final double d9 = cy - dy;
        if (ExpansionArithmetic.twoDiffTail(cy, dy, d9) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[21] = d9;
        final double d11 = cx - dx;
        if (ExpansionArithmetic.twoDiffTail(cx, dx, d11) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[24] = d11;
        final double d14 = bz - dz;
        if (ExpansionArithmetic.twoDiffTail(bz, dz, d14) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[31] = d14;
        final double d20 = az - dz;
        if (ExpansionArithmetic.twoDiffTail(az, dz, d20) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[64] = d20;
        final int e2 = ExpansionArithmetic.expansionTimes(buf, 0, 1, buf, 1, 2, buf, 2, false);
        final int e5 = ExpansionArithmetic.expansionTimes(buf, 4, 5, buf, 5, 6, buf, 6, false);
        final int e6 = ExpansionArithmetic.expansionSum(buf, 2, e2, buf, 6, e5, buf, 8, false, true, false);
        final int e8 = ExpansionArithmetic.expansionTimes(buf, 8, e6, buf, 12, 13, buf, 13, false);
        final int e10 = ExpansionArithmetic.expansionTimes(buf, 0, 1, buf, 21, 22, buf, 22, false);
        final int e12 = ExpansionArithmetic.expansionTimes(buf, 24, 25, buf, 5, 6, buf, 25, false);
        final int e13 = ExpansionArithmetic.expansionSum(buf, 22, e10, buf, 25, e12, buf, 27, false, true, false);
        final int e15 = ExpansionArithmetic.expansionTimes(buf, 27, e13, buf, 31, 32, buf, 32, false);
        final int e16 = ExpansionArithmetic.fastExpansionSum(buf, 13, e8, buf, 32, e15, buf, 40, false, true, false);
        final int e17 = ExpansionArithmetic.expansionTimes(buf, 4, 5, buf, 21, 22, buf, 56, false);
        final int e18 = ExpansionArithmetic.expansionTimes(buf, 24, 25, buf, 1, 2, buf, 58, false);
        final int e19 = ExpansionArithmetic.expansionSum(buf, 56, e17, buf, 58, e18, buf, 60, false, true, false);
        final int e21 = ExpansionArithmetic.expansionTimes(buf, 60, e19, buf, 64, 65, buf, 65, false);
        final int e22 = ExpansionArithmetic.fastExpansionSum(buf, 40, e16, buf, 65, e21, buf, 73, false, false, true);
        return ExpansionArithmetic.signOf(buf, 73, e22);
    }

    static int orient3dStageD(double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double dx, double dy, double dz) {
        final double[] buf = new double[626];
        final int e0 = ExpansionArithmetic.twoDiff(ax, dx, buf, 0, false);
        final int e1 = ExpansionArithmetic.twoDiff(by, dy, buf, 2, false);
        final int e2 = ExpansionArithmetic.expansionTimes(buf, 0, e0, buf, 2, e1, buf, 4, false);
        final int e3 = ExpansionArithmetic.twoDiff(bx, dx, buf, 12, false);
        final int e4 = ExpansionArithmetic.twoDiff(ay, dy, buf, 14, false);
        final int e5 = ExpansionArithmetic.expansionTimes(buf, 12, e3, buf, 14, e4, buf, 16, false);
        final int e6 = ExpansionArithmetic.fastExpansionSum(buf, 4, e2, buf, 16, e5, buf, 24, false, true, false);
        final int e7 = ExpansionArithmetic.twoDiff(cz, dz, buf, 40, false);
        final int e8 = ExpansionArithmetic.expansionTimes(buf, 24, e6, buf, 40, e7, buf, 42, true);
        final int e9 = ExpansionArithmetic.twoDiff(cy, dy, buf, 106, false);
        final int e10 = ExpansionArithmetic.expansionTimes(buf, 0, e0, buf, 106, e9, buf, 108, false);
        final int e11 = ExpansionArithmetic.twoDiff(cx, dx, buf, 116, false);
        final int e12 = ExpansionArithmetic.expansionTimes(buf, 116, e11, buf, 14, e4, buf, 118, false);
        final int e13 = ExpansionArithmetic.fastExpansionSum(buf, 108, e10, buf, 118, e12, buf, 126, false, true, false);
        final int e14 = ExpansionArithmetic.twoDiff(bz, dz, buf, 142, false);
        final int e15 = ExpansionArithmetic.expansionTimes(buf, 126, e13, buf, 142, e14, buf, 144, true);
        final int e16 = ExpansionArithmetic.fastExpansionSum(buf, 42, e8, buf, 144, e15, buf, 208, false, true, true);
        final int e17 = ExpansionArithmetic.expansionTimes(buf, 12, e3, buf, 106, e9, buf, 336, false);
        final int e18 = ExpansionArithmetic.expansionTimes(buf, 116, e11, buf, 2, e1, buf, 344, false);
        final int e19 = ExpansionArithmetic.fastExpansionSum(buf, 336, e17, buf, 344, e18, buf, 352, false, true, false);
        final int e20 = ExpansionArithmetic.twoDiff(az, dz, buf, 368, false);
        final int e21 = ExpansionArithmetic.expansionTimes(buf, 352, e19, buf, 368, e20, buf, 370, true);
        final int e22 = ExpansionArithmetic.fastExpansionSum(buf, 208, e16, buf, 370, e21, buf, 434, false, false, true);
        return ExpansionArithmetic.signOf(buf, 434, e22);
    }

    /** Positive iff {@code d} lies inside the circle through {@code a, b, c} (counterclockwise {@code abc}, y axis up); zero iff cocircular. */
    public static int incircle(double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy) {
        int s = incircleStageA(ax, ay, bx, by, cx, cy, dx, dy);
        if (s != SIGN_UNCERTAIN) {
            return s;
        }
        s = incircleStageB(ax, ay, bx, by, cx, cy, dx, dy);
        if (s != SIGN_UNCERTAIN) {
            return s;
        }
        return incircleStageD(ax, ay, bx, by, cx, cy, dx, dy);
    }

    static int incircleStageA(double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy) {
        final double v2 = ax - dx;
        final double v3 = v2 * v2;
        final double v6 = ay - dy;
        final double v7 = v6 * v6;
        final double v8 = v3 + v7;
        final double v10 = bx - dx;
        final double v12 = cy - dy;
        final double v13 = v10 * v12;
        final double v15 = by - dy;
        final double v17 = cx - dx;
        final double v18 = v15 * v17;
        final double v19 = v13 - v18;
        final double v20 = v8 * v19;
        final double v21 = v10 * v10;
        final double v22 = v15 * v15;
        final double v23 = v21 + v22;
        final double v24 = v2 * v12;
        final double v25 = v6 * v17;
        final double v26 = v24 - v25;
        final double v27 = v23 * v26;
        final double v28 = v20 - v27;
        final double v29 = v17 * v17;
        final double v30 = v12 * v12;
        final double v31 = v29 + v30;
        final double v32 = v2 * v15;
        final double v33 = v6 * v10;
        final double v34 = v32 - v33;
        final double v35 = v31 * v34;
        final double v36 = v28 + v35;
        final double v38 = Math.abs(v3);
        final double v39 = Math.abs(v7);
        final double v40 = v38 + v39;
        final double v42 = v40 + 0x1.0p-1021;
        final double v43 = Math.abs(v13);
        final double v44 = Math.abs(v18);
        final double v45 = v43 + v44;
        final double v46 = v45 + 0x1.0p-1021;
        final double v47 = v42 * v46;
        final double v48 = Math.abs(v21);
        final double v49 = Math.abs(v22);
        final double v50 = v48 + v49;
        final double v51 = v50 + 0x1.0p-1021;
        final double v52 = Math.abs(v24);
        final double v53 = Math.abs(v25);
        final double v54 = v52 + v53;
        final double v55 = v54 + 0x1.0p-1021;
        final double v56 = v51 * v55;
        final double v57 = v47 + v56;
        final double v58 = Math.abs(v29);
        final double v59 = Math.abs(v30);
        final double v60 = v58 + v59;
        final double v61 = v60 + 0x1.0p-1021;
        final double v62 = Math.abs(v32);
        final double v63 = Math.abs(v33);
        final double v64 = v62 + v63;
        final double v65 = v64 + 0x1.0p-1021;
        final double v66 = v61 * v65;
        final double v67 = v57 + v66;
        final double v69 = v67 + 0x1.8p-1021;
        final double v70 = 0x1.3ffffff4afb15p-50 * v69;
        if (v36 > v70) {
            return 1;
        }
        if (v36 < -v70) {
            return -1;
        }
        if (v70 == 0.0 && v36 == 0.0) {
            return 0;
        }
        return SIGN_UNCERTAIN;
    }

    static int incircleStageB(double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy) {
        final double[] buf = new double[310];
        final double d0 = ax - dx;
        if (ExpansionArithmetic.twoDiffTail(ax, dx, d0) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[0] = d0;
        final double d2 = ay - dy;
        if (ExpansionArithmetic.twoDiffTail(ay, dy, d2) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[3] = d2;
        final double d5 = bx - dx;
        if (ExpansionArithmetic.twoDiffTail(bx, dx, d5) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[10] = d5;
        final double d6 = cy - dy;
        if (ExpansionArithmetic.twoDiffTail(cy, dy, d6) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[11] = d6;
        final double d8 = by - dy;
        if (ExpansionArithmetic.twoDiffTail(by, dy, d8) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[14] = d8;
        final double d9 = cx - dx;
        if (ExpansionArithmetic.twoDiffTail(cx, dx, d9) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[15] = d9;
        final int e1 = ExpansionArithmetic.expansionTimes(buf, 0, 1, buf, 0, 1, buf, 1, false);
        final int e3 = ExpansionArithmetic.expansionTimes(buf, 3, 4, buf, 3, 4, buf, 4, false);
        final int e4 = ExpansionArithmetic.expansionSum(buf, 1, e1, buf, 4, e3, buf, 6, false, false, false);
        final int e7 = ExpansionArithmetic.expansionTimes(buf, 10, 11, buf, 11, 12, buf, 12, false);
        final int e10 = ExpansionArithmetic.expansionTimes(buf, 14, 15, buf, 15, 16, buf, 16, false);
        final int e11 = ExpansionArithmetic.expansionSum(buf, 12, e7, buf, 16, e10, buf, 18, false, true, false);
        final int e12 = ExpansionArithmetic.expansionTimes(buf, 6, e4, buf, 18, e11, buf, 22, true);
        final int e13 = ExpansionArithmetic.expansionTimes(buf, 10, 11, buf, 10, 11, buf, 54, false);
        final int e14 = ExpansionArithmetic.expansionTimes(buf, 14, 15, buf, 14, 15, buf, 56, false);
        final int e15 = ExpansionArithmetic.expansionSum(buf, 54, e13, buf, 56, e14, buf, 58, false, false, false);
        final int e16 = ExpansionArithmetic.expansionTimes(buf, 0, 1, buf, 11, 12, buf, 62, false);
        final int e17 = ExpansionArithmetic.expansionTimes(buf, 3, 4, buf, 15, 16, buf, 64, false);
        final int e18 = ExpansionArithmetic.expansionSum(buf, 62, e16, buf, 64, e17, buf, 66, false, true, false);
        final int e19 = ExpansionArithmetic.expansionTimes(buf, 58, e15, buf, 66, e18, buf, 70, true);
        final int e20 = ExpansionArithmetic.fastExpansionSum(buf, 22, e12, buf, 70, e19, buf, 102, false, true, true);
        final int e21 = ExpansionArithmetic.expansionTimes(buf, 15, 16, buf, 15, 16, buf, 166, false);
        final int e22 = ExpansionArithmetic.expansionTimes(buf, 11, 12, buf, 11, 12, buf, 168, false);
        final int e23 = ExpansionArithmetic.expansionSum(buf, 166, e21, buf, 168, e22, buf, 170, false, false, false);
        final int e24 = ExpansionArithmetic.expansionTimes(buf, 0, 1, buf, 14, 15, buf, 174, false);
        final int e25 = ExpansionArithmetic.expansionTimes(buf, 3, 4, buf, 10, 11, buf, 176, false);
        final int e26 = ExpansionArithmetic.expansionSum(buf, 174, e24, buf, 176, e25, buf, 178, false, true, false);
        final int e27 = ExpansionArithmetic.expansionTimes(buf, 170, e23, buf, 178, e26, buf, 182, true);
        final int e28 = ExpansionArithmetic.fastExpansionSum(buf, 102, e20, buf, 182, e27, buf, 214, false, false, true);
        return ExpansionArithmetic.signOf(buf, 214, e28);
    }

    static int incircleStageD(double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy) {
        final double[] buf = new double[3252];
        final int e0 = ExpansionArithmetic.twoDiff(ax, dx, buf, 0, false);
        final int e1 = ExpansionArithmetic.twoSquare(buf, 0, e0, buf, 2, false);
        final int e2 = ExpansionArithmetic.twoDiff(ay, dy, buf, 8, false);
        final int e3 = ExpansionArithmetic.twoSquare(buf, 8, e2, buf, 10, false);
        final int e4 = ExpansionArithmetic.fastExpansionSum(buf, 2, e1, buf, 10, e3, buf, 16, false, false, false);
        final int e5 = ExpansionArithmetic.twoDiff(bx, dx, buf, 28, false);
        final int e6 = ExpansionArithmetic.twoDiff(cy, dy, buf, 30, false);
        final int e7 = ExpansionArithmetic.expansionTimes(buf, 28, e5, buf, 30, e6, buf, 32, false);
        final int e8 = ExpansionArithmetic.twoDiff(by, dy, buf, 40, false);
        final int e9 = ExpansionArithmetic.twoDiff(cx, dx, buf, 42, false);
        final int e10 = ExpansionArithmetic.expansionTimes(buf, 40, e8, buf, 42, e9, buf, 44, false);
        final int e11 = ExpansionArithmetic.fastExpansionSum(buf, 32, e7, buf, 44, e10, buf, 52, false, true, false);
        final int e12 = ExpansionArithmetic.expansionTimes(buf, 16, e4, buf, 52, e11, buf, 68, true);
        final int e13 = ExpansionArithmetic.twoSquare(buf, 28, e5, buf, 452, false);
        final int e14 = ExpansionArithmetic.twoSquare(buf, 40, e8, buf, 458, false);
        final int e15 = ExpansionArithmetic.fastExpansionSum(buf, 452, e13, buf, 458, e14, buf, 464, false, false, false);
        final int e16 = ExpansionArithmetic.expansionTimes(buf, 0, e0, buf, 30, e6, buf, 476, false);
        final int e17 = ExpansionArithmetic.expansionTimes(buf, 8, e2, buf, 42, e9, buf, 484, false);
        final int e18 = ExpansionArithmetic.fastExpansionSum(buf, 476, e16, buf, 484, e17, buf, 492, false, true, false);
        final int e19 = ExpansionArithmetic.expansionTimes(buf, 464, e15, buf, 492, e18, buf, 508, true);
        final int e20 = ExpansionArithmetic.fastExpansionSum(buf, 68, e12, buf, 508, e19, buf, 892, false, true, true);
        final int e21 = ExpansionArithmetic.twoSquare(buf, 42, e9, buf, 1660, false);
        final int e22 = ExpansionArithmetic.twoSquare(buf, 30, e6, buf, 1666, false);
        final int e23 = ExpansionArithmetic.fastExpansionSum(buf, 1660, e21, buf, 1666, e22, buf, 1672, false, false, false);
        final int e24 = ExpansionArithmetic.expansionTimes(buf, 0, e0, buf, 40, e8, buf, 1684, false);
        final int e25 = ExpansionArithmetic.expansionTimes(buf, 8, e2, buf, 28, e5, buf, 1692, false);
        final int e26 = ExpansionArithmetic.fastExpansionSum(buf, 1684, e24, buf, 1692, e25, buf, 1700, false, true, false);
        final int e27 = ExpansionArithmetic.expansionTimes(buf, 1672, e23, buf, 1700, e26, buf, 1716, true);
        final int e28 = ExpansionArithmetic.fastExpansionSum(buf, 892, e20, buf, 1716, e27, buf, 2100, false, false, true);
        return ExpansionArithmetic.signOf(buf, 2100, e28);
    }

    /** Sign of {@code (a-p) dot (b-p)}. Negative iff {@code p} lies inside the circle having {@code ab} as its diameter; zero iff {@code p} lies on that circle (equivalently, {@code angle apb} is a right angle). */
    public static int diametralCircle2d(double ax, double ay, double bx, double by, double px, double py) {
        int s = diametralCircle2dStageA(ax, ay, bx, by, px, py);
        if (s != SIGN_UNCERTAIN) {
            return s;
        }
        s = diametralCircle2dStageB(ax, ay, bx, by, px, py);
        if (s != SIGN_UNCERTAIN) {
            return s;
        }
        return diametralCircle2dStageD(ax, ay, bx, by, px, py);
    }

    static int diametralCircle2dStageA(double ax, double ay, double bx, double by, double px, double py) {
        final double v2 = ax - px;
        final double v4 = bx - px;
        final double v5 = v2 * v4;
        final double v8 = ay - py;
        final double v10 = by - py;
        final double v11 = v8 * v10;
        final double v12 = v5 + v11;
        final double v14 = Math.abs(v5);
        final double v15 = Math.abs(v11);
        final double v16 = v14 + v15;
        final double v18 = v16 + 0x1.0p-1021;
        final double v19 = 0x1.7fffffe95f621p-52 * v18;
        if (v12 > v19) {
            return 1;
        }
        if (v12 < -v19) {
            return -1;
        }
        if (v19 == 0.0 && v12 == 0.0) {
            return 0;
        }
        return SIGN_UNCERTAIN;
    }

    static int diametralCircle2dStageB(double ax, double ay, double bx, double by, double px, double py) {
        final double[] buf = new double[12];
        final double d0 = ax - px;
        if (ExpansionArithmetic.twoDiffTail(ax, px, d0) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[0] = d0;
        final double d1 = bx - px;
        if (ExpansionArithmetic.twoDiffTail(bx, px, d1) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[1] = d1;
        final double d3 = ay - py;
        if (ExpansionArithmetic.twoDiffTail(ay, py, d3) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[4] = d3;
        final double d4 = by - py;
        if (ExpansionArithmetic.twoDiffTail(by, py, d4) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[5] = d4;
        final int e2 = ExpansionArithmetic.expansionTimes(buf, 0, 1, buf, 1, 2, buf, 2, false);
        final int e5 = ExpansionArithmetic.expansionTimes(buf, 4, 5, buf, 5, 6, buf, 6, false);
        final int e6 = ExpansionArithmetic.expansionSum(buf, 2, e2, buf, 6, e5, buf, 8, false, false, false);
        return ExpansionArithmetic.signOf(buf, 8, e6);
    }

    static int diametralCircle2dStageD(double ax, double ay, double bx, double by, double px, double py) {
        final double[] buf = new double[40];
        final int e0 = ExpansionArithmetic.twoDiff(ax, px, buf, 0, false);
        final int e1 = ExpansionArithmetic.twoDiff(bx, px, buf, 2, false);
        final int e2 = ExpansionArithmetic.expansionTimes(buf, 0, e0, buf, 2, e1, buf, 4, false);
        final int e3 = ExpansionArithmetic.twoDiff(ay, py, buf, 12, false);
        final int e4 = ExpansionArithmetic.twoDiff(by, py, buf, 14, false);
        final int e5 = ExpansionArithmetic.expansionTimes(buf, 12, e3, buf, 14, e4, buf, 16, false);
        final int e6 = ExpansionArithmetic.fastExpansionSum(buf, 4, e2, buf, 16, e5, buf, 24, false, false, false);
        return ExpansionArithmetic.signOf(buf, 24, e6);
    }

    /** Positive iff {@code e} lies inside the sphere through {@code a, b, c, d}, where the four points are ordered so that {@code orient3d(a, b, c, d)} is positive; zero iff cospherical. */
    public static int insphere(double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double dx, double dy, double dz, double ex, double ey, double ez) {
        int s = insphereStageA(ax, ay, az, bx, by, bz, cx, cy, cz, dx, dy, dz, ex, ey, ez);
        if (s != SIGN_UNCERTAIN) {
            return s;
        }
        s = insphereStageB(ax, ay, az, bx, by, bz, cx, cy, cz, dx, dy, dz, ex, ey, ez);
        if (s != SIGN_UNCERTAIN) {
            return s;
        }
        return insphereStageD(ax, ay, az, bx, by, bz, cx, cy, cz, dx, dy, dz, ex, ey, ez);
    }

    static int insphereStageA(double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double dx, double dy, double dz, double ex, double ey, double ez) {
        final double v2 = dx - ex;
        final double v5 = cy - ey;
        final double v6 = v2 * v5;
        final double v8 = cx - ex;
        final double v10 = dy - ey;
        final double v11 = v8 * v10;
        final double v12 = v6 - v11;
        final double v15 = bz - ez;
        final double v16 = v12 * v15;
        final double v18 = by - ey;
        final double v19 = v2 * v18;
        final double v21 = bx - ex;
        final double v22 = v21 * v10;
        final double v23 = v19 - v22;
        final double v25 = cz - ez;
        final double v26 = v23 * v25;
        final double v27 = v16 - v26;
        final double v28 = v8 * v18;
        final double v29 = v21 * v5;
        final double v30 = v28 - v29;
        final double v32 = dz - ez;
        final double v33 = v30 * v32;
        final double v34 = v27 + v33;
        final double v36 = ax - ex;
        final double v37 = v36 * v36;
        final double v39 = ay - ey;
        final double v40 = v39 * v39;
        final double v41 = v37 + v40;
        final double v43 = az - ez;
        final double v44 = v43 * v43;
        final double v45 = v41 + v44;
        final double v46 = v34 * v45;
        final double v47 = v12 * v43;
        final double v48 = v2 * v39;
        final double v49 = v36 * v10;
        final double v50 = v48 - v49;
        final double v51 = v50 * v25;
        final double v52 = v47 - v51;
        final double v53 = v8 * v39;
        final double v54 = v36 * v5;
        final double v55 = v53 - v54;
        final double v56 = v55 * v32;
        final double v57 = v52 + v56;
        final double v58 = v21 * v21;
        final double v59 = v18 * v18;
        final double v60 = v58 + v59;
        final double v61 = v15 * v15;
        final double v62 = v60 + v61;
        final double v63 = v57 * v62;
        final double v64 = v46 - v63;
        final double v65 = v23 * v43;
        final double v66 = v50 * v15;
        final double v67 = v65 - v66;
        final double v68 = v21 * v39;
        final double v69 = v36 * v18;
        final double v70 = v68 - v69;
        final double v71 = v70 * v32;
        final double v72 = v67 + v71;
        final double v73 = v8 * v8;
        final double v74 = v5 * v5;
        final double v75 = v73 + v74;
        final double v76 = v25 * v25;
        final double v77 = v75 + v76;
        final double v78 = v72 * v77;
        final double v79 = v64 + v78;
        final double v80 = v30 * v43;
        final double v81 = v55 * v15;
        final double v82 = v80 - v81;
        final double v83 = v70 * v25;
        final double v84 = v82 + v83;
        final double v85 = v2 * v2;
        final double v86 = v10 * v10;
        final double v87 = v85 + v86;
        final double v88 = v32 * v32;
        final double v89 = v87 + v88;
        final double v90 = v84 * v89;
        final double v91 = v79 - v90;
        final double v93 = Math.abs(v6);
        final double v94 = Math.abs(v11);
        final double v95 = v93 + v94;
        final double v97 = v95 + 0x1.0p-1021;
        final double v98 = Math.abs(v15);
        final double v99 = v97 * v98;
        final double v100 = Math.abs(v19);
        final double v101 = Math.abs(v22);
        final double v102 = v100 + v101;
        final double v103 = v102 + 0x1.0p-1021;
        final double v104 = Math.abs(v25);
        final double v105 = v103 * v104;
        final double v106 = v99 + v105;
        final double v107 = Math.abs(v28);
        final double v108 = Math.abs(v29);
        final double v109 = v107 + v108;
        final double v110 = v109 + 0x1.0p-1021;
        final double v111 = Math.abs(v32);
        final double v112 = v110 * v111;
        final double v113 = v106 + v112;
        final double v115 = v113 + 0x1.8p-1021;
        final double v116 = Math.abs(v37);
        final double v117 = Math.abs(v40);
        final double v118 = v116 + v117;
        final double v119 = Math.abs(v44);
        final double v120 = v118 + v119;
        final double v121 = v120 + 0x1.8p-1021;
        final double v122 = v115 * v121;
        final double v123 = Math.abs(v43);
        final double v124 = v97 * v123;
        final double v125 = Math.abs(v48);
        final double v126 = Math.abs(v49);
        final double v127 = v125 + v126;
        final double v128 = v127 + 0x1.0p-1021;
        final double v129 = v128 * v104;
        final double v130 = v124 + v129;
        final double v131 = Math.abs(v53);
        final double v132 = Math.abs(v54);
        final double v133 = v131 + v132;
        final double v134 = v133 + 0x1.0p-1021;
        final double v135 = v134 * v111;
        final double v136 = v130 + v135;
        final double v137 = v136 + 0x1.8p-1021;
        final double v138 = Math.abs(v58);
        final double v139 = Math.abs(v59);
        final double v140 = v138 + v139;
        final double v141 = Math.abs(v61);
        final double v142 = v140 + v141;
        final double v143 = v142 + 0x1.8p-1021;
        final double v144 = v137 * v143;
        final double v145 = v122 + v144;
        final double v146 = v103 * v123;
        final double v147 = v128 * v98;
        final double v148 = v146 + v147;
        final double v149 = Math.abs(v68);
        final double v150 = Math.abs(v69);
        final double v151 = v149 + v150;
        final double v152 = v151 + 0x1.0p-1021;
        final double v153 = v152 * v111;
        final double v154 = v148 + v153;
        final double v155 = v154 + 0x1.8p-1021;
        final double v156 = Math.abs(v73);
        final double v157 = Math.abs(v74);
        final double v158 = v156 + v157;
        final double v159 = Math.abs(v76);
        final double v160 = v158 + v159;
        final double v161 = v160 + 0x1.8p-1021;
        final double v162 = v155 * v161;
        final double v163 = v145 + v162;
        final double v164 = v110 * v123;
        final double v165 = v134 * v98;
        final double v166 = v164 + v165;
        final double v167 = v152 * v104;
        final double v168 = v166 + v167;
        final double v169 = v168 + 0x1.8p-1021;
        final double v170 = Math.abs(v85);
        final double v171 = Math.abs(v86);
        final double v172 = v170 + v171;
        final double v173 = Math.abs(v88);
        final double v174 = v172 + v173;
        final double v175 = v174 + 0x1.8p-1021;
        final double v176 = v169 * v175;
        final double v177 = v163 + v176;
        final double v179 = v177 + 0x1.0p-1020;
        final double v180 = 0x1.fffffff4afb1ap-50 * v179;
        if (v91 > v180) {
            return 1;
        }
        if (v91 < -v180) {
            return -1;
        }
        if (v180 == 0.0 && v91 == 0.0) {
            return 0;
        }
        return SIGN_UNCERTAIN;
    }

    static int insphereStageB(double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double dx, double dy, double dz, double ex, double ey, double ez) {
        final double[] buf = new double[4124];
        final double d0 = dx - ex;
        if (ExpansionArithmetic.twoDiffTail(dx, ex, d0) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[0] = d0;
        final double d1 = cy - ey;
        if (ExpansionArithmetic.twoDiffTail(cy, ey, d1) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[1] = d1;
        final double d3 = cx - ex;
        if (ExpansionArithmetic.twoDiffTail(cx, ex, d3) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[4] = d3;
        final double d4 = dy - ey;
        if (ExpansionArithmetic.twoDiffTail(dy, ey, d4) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[5] = d4;
        final double d7 = bz - ez;
        if (ExpansionArithmetic.twoDiffTail(bz, ez, d7) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[12] = d7;
        final double d9 = by - ey;
        if (ExpansionArithmetic.twoDiffTail(by, ey, d9) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[21] = d9;
        final double d11 = bx - ex;
        if (ExpansionArithmetic.twoDiffTail(bx, ex, d11) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[24] = d11;
        final double d14 = cz - ez;
        if (ExpansionArithmetic.twoDiffTail(cz, ez, d14) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[31] = d14;
        final double d20 = dz - ez;
        if (ExpansionArithmetic.twoDiffTail(dz, ez, d20) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[64] = d20;
        final double d23 = ax - ex;
        if (ExpansionArithmetic.twoDiffTail(ax, ex, d23) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[97] = d23;
        final double d25 = ay - ey;
        if (ExpansionArithmetic.twoDiffTail(ay, ey, d25) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[100] = d25;
        final double d28 = az - ez;
        if (ExpansionArithmetic.twoDiffTail(az, ez, d28) != 0.0) {
            return SIGN_UNCERTAIN;
        }
        buf[107] = d28;
        final int e2 = ExpansionArithmetic.expansionTimes(buf, 0, 1, buf, 1, 2, buf, 2, false);
        final int e5 = ExpansionArithmetic.expansionTimes(buf, 4, 5, buf, 5, 6, buf, 6, false);
        final int e6 = ExpansionArithmetic.expansionSum(buf, 2, e2, buf, 6, e5, buf, 8, false, true, false);
        final int e8 = ExpansionArithmetic.expansionTimes(buf, 8, e6, buf, 12, 13, buf, 13, false);
        final int e10 = ExpansionArithmetic.expansionTimes(buf, 0, 1, buf, 21, 22, buf, 22, false);
        final int e12 = ExpansionArithmetic.expansionTimes(buf, 24, 25, buf, 5, 6, buf, 25, false);
        final int e13 = ExpansionArithmetic.expansionSum(buf, 22, e10, buf, 25, e12, buf, 27, false, true, false);
        final int e15 = ExpansionArithmetic.expansionTimes(buf, 27, e13, buf, 31, 32, buf, 32, false);
        final int e16 = ExpansionArithmetic.fastExpansionSum(buf, 13, e8, buf, 32, e15, buf, 40, false, true, false);
        final int e17 = ExpansionArithmetic.expansionTimes(buf, 4, 5, buf, 21, 22, buf, 56, false);
        final int e18 = ExpansionArithmetic.expansionTimes(buf, 24, 25, buf, 1, 2, buf, 58, false);
        final int e19 = ExpansionArithmetic.expansionSum(buf, 56, e17, buf, 58, e18, buf, 60, false, true, false);
        final int e21 = ExpansionArithmetic.expansionTimes(buf, 60, e19, buf, 64, 65, buf, 65, false);
        final int e22 = ExpansionArithmetic.fastExpansionSum(buf, 40, e16, buf, 65, e21, buf, 73, false, false, true);
        final int e24 = ExpansionArithmetic.expansionTimes(buf, 97, 98, buf, 97, 98, buf, 98, false);
        final int e26 = ExpansionArithmetic.expansionTimes(buf, 100, 101, buf, 100, 101, buf, 101, false);
        final int e27 = ExpansionArithmetic.expansionSum(buf, 98, e24, buf, 101, e26, buf, 103, false, false, false);
        final int e29 = ExpansionArithmetic.expansionTimes(buf, 107, 108, buf, 107, 108, buf, 108, false);
        final int e30 = ExpansionArithmetic.expansionSum(buf, 103, e27, buf, 108, e29, buf, 110, false, false, false);
        final int e31 = ExpansionArithmetic.expansionTimes(buf, 73, e22, buf, 110, e30, buf, 116, true);
        final int e32 = ExpansionArithmetic.expansionTimes(buf, 8, e6, buf, 107, 108, buf, 404, false);
        final int e33 = ExpansionArithmetic.expansionTimes(buf, 0, 1, buf, 100, 101, buf, 412, false);
        final int e34 = ExpansionArithmetic.expansionTimes(buf, 97, 98, buf, 5, 6, buf, 414, false);
        final int e35 = ExpansionArithmetic.expansionSum(buf, 412, e33, buf, 414, e34, buf, 416, false, true, false);
        final int e36 = ExpansionArithmetic.expansionTimes(buf, 416, e35, buf, 31, 32, buf, 420, false);
        final int e37 = ExpansionArithmetic.fastExpansionSum(buf, 404, e32, buf, 420, e36, buf, 428, false, true, false);
        final int e38 = ExpansionArithmetic.expansionTimes(buf, 4, 5, buf, 100, 101, buf, 444, false);
        final int e39 = ExpansionArithmetic.expansionTimes(buf, 97, 98, buf, 1, 2, buf, 446, false);
        final int e40 = ExpansionArithmetic.expansionSum(buf, 444, e38, buf, 446, e39, buf, 448, false, true, false);
        final int e41 = ExpansionArithmetic.expansionTimes(buf, 448, e40, buf, 64, 65, buf, 452, false);
        final int e42 = ExpansionArithmetic.fastExpansionSum(buf, 428, e37, buf, 452, e41, buf, 460, false, false, true);
        final int e43 = ExpansionArithmetic.expansionTimes(buf, 24, 25, buf, 24, 25, buf, 484, false);
        final int e44 = ExpansionArithmetic.expansionTimes(buf, 21, 22, buf, 21, 22, buf, 486, false);
        final int e45 = ExpansionArithmetic.expansionSum(buf, 484, e43, buf, 486, e44, buf, 488, false, false, false);
        final int e46 = ExpansionArithmetic.expansionTimes(buf, 12, 13, buf, 12, 13, buf, 492, false);
        final int e47 = ExpansionArithmetic.expansionSum(buf, 488, e45, buf, 492, e46, buf, 494, false, false, false);
        final int e48 = ExpansionArithmetic.expansionTimes(buf, 460, e42, buf, 494, e47, buf, 500, true);
        final int e49 = ExpansionArithmetic.fastExpansionSum(buf, 116, e31, buf, 500, e48, buf, 788, false, true, true);
        final int e50 = ExpansionArithmetic.expansionTimes(buf, 27, e13, buf, 107, 108, buf, 1364, false);
        final int e51 = ExpansionArithmetic.expansionTimes(buf, 416, e35, buf, 12, 13, buf, 1372, false);
        final int e52 = ExpansionArithmetic.fastExpansionSum(buf, 1364, e50, buf, 1372, e51, buf, 1380, false, true, false);
        final int e53 = ExpansionArithmetic.expansionTimes(buf, 24, 25, buf, 100, 101, buf, 1396, false);
        final int e54 = ExpansionArithmetic.expansionTimes(buf, 97, 98, buf, 21, 22, buf, 1398, false);
        final int e55 = ExpansionArithmetic.expansionSum(buf, 1396, e53, buf, 1398, e54, buf, 1400, false, true, false);
        final int e56 = ExpansionArithmetic.expansionTimes(buf, 1400, e55, buf, 64, 65, buf, 1404, false);
        final int e57 = ExpansionArithmetic.fastExpansionSum(buf, 1380, e52, buf, 1404, e56, buf, 1412, false, false, true);
        final int e58 = ExpansionArithmetic.expansionTimes(buf, 4, 5, buf, 4, 5, buf, 1436, false);
        final int e59 = ExpansionArithmetic.expansionTimes(buf, 1, 2, buf, 1, 2, buf, 1438, false);
        final int e60 = ExpansionArithmetic.expansionSum(buf, 1436, e58, buf, 1438, e59, buf, 1440, false, false, false);
        final int e61 = ExpansionArithmetic.expansionTimes(buf, 31, 32, buf, 31, 32, buf, 1444, false);
        final int e62 = ExpansionArithmetic.expansionSum(buf, 1440, e60, buf, 1444, e61, buf, 1446, false, false, false);
        final int e63 = ExpansionArithmetic.expansionTimes(buf, 1412, e57, buf, 1446, e62, buf, 1452, true);
        final int e64 = ExpansionArithmetic.fastExpansionSum(buf, 788, e49, buf, 1452, e63, buf, 1740, false, false, true);
        final int e65 = ExpansionArithmetic.expansionTimes(buf, 60, e19, buf, 107, 108, buf, 2604, false);
        final int e66 = ExpansionArithmetic.expansionTimes(buf, 448, e40, buf, 12, 13, buf, 2612, false);
        final int e67 = ExpansionArithmetic.fastExpansionSum(buf, 2604, e65, buf, 2612, e66, buf, 2620, false, true, false);
        final int e68 = ExpansionArithmetic.expansionTimes(buf, 1400, e55, buf, 31, 32, buf, 2636, false);
        final int e69 = ExpansionArithmetic.fastExpansionSum(buf, 2620, e67, buf, 2636, e68, buf, 2644, false, false, true);
        final int e70 = ExpansionArithmetic.expansionTimes(buf, 0, 1, buf, 0, 1, buf, 2668, false);
        final int e71 = ExpansionArithmetic.expansionTimes(buf, 5, 6, buf, 5, 6, buf, 2670, false);
        final int e72 = ExpansionArithmetic.expansionSum(buf, 2668, e70, buf, 2670, e71, buf, 2672, false, false, false);
        final int e73 = ExpansionArithmetic.expansionTimes(buf, 64, 65, buf, 64, 65, buf, 2676, false);
        final int e74 = ExpansionArithmetic.expansionSum(buf, 2672, e72, buf, 2676, e73, buf, 2678, false, false, false);
        final int e75 = ExpansionArithmetic.expansionTimes(buf, 2644, e69, buf, 2678, e74, buf, 2684, true);
        final int e76 = ExpansionArithmetic.fastExpansionSum(buf, 1740, e64, buf, 2684, e75, buf, 2972, false, true, true);
        return ExpansionArithmetic.signOf(buf, 2972, e76);
    }

    static int insphereStageD(double ax, double ay, double az, double bx, double by, double bz, double cx, double cy, double cz, double dx, double dy, double dz, double ex, double ey, double ez) {
        final double[] buf = new double[92312];
        final int e0 = ExpansionArithmetic.twoDiff(dx, ex, buf, 0, false);
        final int e1 = ExpansionArithmetic.twoDiff(cy, ey, buf, 2, false);
        final int e2 = ExpansionArithmetic.expansionTimes(buf, 0, e0, buf, 2, e1, buf, 4, false);
        final int e3 = ExpansionArithmetic.twoDiff(cx, ex, buf, 12, false);
        final int e4 = ExpansionArithmetic.twoDiff(dy, ey, buf, 14, false);
        final int e5 = ExpansionArithmetic.expansionTimes(buf, 12, e3, buf, 14, e4, buf, 16, false);
        final int e6 = ExpansionArithmetic.fastExpansionSum(buf, 4, e2, buf, 16, e5, buf, 24, false, true, false);
        final int e7 = ExpansionArithmetic.twoDiff(bz, ez, buf, 40, false);
        final int e8 = ExpansionArithmetic.expansionTimes(buf, 24, e6, buf, 40, e7, buf, 42, true);
        final int e9 = ExpansionArithmetic.twoDiff(by, ey, buf, 106, false);
        final int e10 = ExpansionArithmetic.expansionTimes(buf, 0, e0, buf, 106, e9, buf, 108, false);
        final int e11 = ExpansionArithmetic.twoDiff(bx, ex, buf, 116, false);
        final int e12 = ExpansionArithmetic.expansionTimes(buf, 116, e11, buf, 14, e4, buf, 118, false);
        final int e13 = ExpansionArithmetic.fastExpansionSum(buf, 108, e10, buf, 118, e12, buf, 126, false, true, false);
        final int e14 = ExpansionArithmetic.twoDiff(cz, ez, buf, 142, false);
        final int e15 = ExpansionArithmetic.expansionTimes(buf, 126, e13, buf, 142, e14, buf, 144, true);
        final int e16 = ExpansionArithmetic.fastExpansionSum(buf, 42, e8, buf, 144, e15, buf, 208, false, true, true);
        final int e17 = ExpansionArithmetic.expansionTimes(buf, 12, e3, buf, 106, e9, buf, 336, false);
        final int e18 = ExpansionArithmetic.expansionTimes(buf, 116, e11, buf, 2, e1, buf, 344, false);
        final int e19 = ExpansionArithmetic.fastExpansionSum(buf, 336, e17, buf, 344, e18, buf, 352, false, true, false);
        final int e20 = ExpansionArithmetic.twoDiff(dz, ez, buf, 368, false);
        final int e21 = ExpansionArithmetic.expansionTimes(buf, 352, e19, buf, 368, e20, buf, 370, true);
        final int e22 = ExpansionArithmetic.fastExpansionSum(buf, 208, e16, buf, 370, e21, buf, 434, false, false, true);
        final int e23 = ExpansionArithmetic.twoDiff(ax, ex, buf, 626, false);
        final int e24 = ExpansionArithmetic.twoSquare(buf, 626, e23, buf, 628, false);
        final int e25 = ExpansionArithmetic.twoDiff(ay, ey, buf, 634, false);
        final int e26 = ExpansionArithmetic.twoSquare(buf, 634, e25, buf, 636, false);
        final int e27 = ExpansionArithmetic.fastExpansionSum(buf, 628, e24, buf, 636, e26, buf, 642, false, false, false);
        final int e28 = ExpansionArithmetic.twoDiff(az, ez, buf, 654, false);
        final int e29 = ExpansionArithmetic.twoSquare(buf, 654, e28, buf, 656, false);
        final int e30 = ExpansionArithmetic.fastExpansionSum(buf, 642, e27, buf, 656, e29, buf, 662, false, false, true);
        final int e31 = ExpansionArithmetic.expansionTimes(buf, 434, e22, buf, 662, e30, buf, 680, true);
        final int e32 = ExpansionArithmetic.expansionTimes(buf, 24, e6, buf, 654, e28, buf, 7592, true);
        final int e33 = ExpansionArithmetic.expansionTimes(buf, 0, e0, buf, 634, e25, buf, 7656, false);
        final int e34 = ExpansionArithmetic.expansionTimes(buf, 626, e23, buf, 14, e4, buf, 7664, false);
        final int e35 = ExpansionArithmetic.fastExpansionSum(buf, 7656, e33, buf, 7664, e34, buf, 7672, false, true, false);
        final int e36 = ExpansionArithmetic.expansionTimes(buf, 7672, e35, buf, 142, e14, buf, 7688, true);
        final int e37 = ExpansionArithmetic.fastExpansionSum(buf, 7592, e32, buf, 7688, e36, buf, 7752, false, true, true);
        final int e38 = ExpansionArithmetic.expansionTimes(buf, 12, e3, buf, 634, e25, buf, 7880, false);
        final int e39 = ExpansionArithmetic.expansionTimes(buf, 626, e23, buf, 2, e1, buf, 7888, false);
        final int e40 = ExpansionArithmetic.fastExpansionSum(buf, 7880, e38, buf, 7888, e39, buf, 7896, false, true, false);
        final int e41 = ExpansionArithmetic.expansionTimes(buf, 7896, e40, buf, 368, e20, buf, 7912, true);
        final int e42 = ExpansionArithmetic.fastExpansionSum(buf, 7752, e37, buf, 7912, e41, buf, 7976, false, false, true);
        final int e43 = ExpansionArithmetic.twoSquare(buf, 116, e11, buf, 8168, false);
        final int e44 = ExpansionArithmetic.twoSquare(buf, 106, e9, buf, 8174, false);
        final int e45 = ExpansionArithmetic.fastExpansionSum(buf, 8168, e43, buf, 8174, e44, buf, 8180, false, false, false);
        final int e46 = ExpansionArithmetic.twoSquare(buf, 40, e7, buf, 8192, false);
        final int e47 = ExpansionArithmetic.fastExpansionSum(buf, 8180, e45, buf, 8192, e46, buf, 8198, false, false, true);
        final int e48 = ExpansionArithmetic.expansionTimes(buf, 7976, e42, buf, 8198, e47, buf, 8216, true);
        final int e49 = ExpansionArithmetic.fastExpansionSum(buf, 680, e31, buf, 8216, e48, buf, 15128, false, true, true);
        final int e50 = ExpansionArithmetic.expansionTimes(buf, 126, e13, buf, 654, e28, buf, 28952, true);
        final int e51 = ExpansionArithmetic.expansionTimes(buf, 7672, e35, buf, 40, e7, buf, 29016, true);
        final int e52 = ExpansionArithmetic.fastExpansionSum(buf, 28952, e50, buf, 29016, e51, buf, 29080, false, true, true);
        final int e53 = ExpansionArithmetic.expansionTimes(buf, 116, e11, buf, 634, e25, buf, 29208, false);
        final int e54 = ExpansionArithmetic.expansionTimes(buf, 626, e23, buf, 106, e9, buf, 29216, false);
        final int e55 = ExpansionArithmetic.fastExpansionSum(buf, 29208, e53, buf, 29216, e54, buf, 29224, false, true, false);
        final int e56 = ExpansionArithmetic.expansionTimes(buf, 29224, e55, buf, 368, e20, buf, 29240, true);
        final int e57 = ExpansionArithmetic.fastExpansionSum(buf, 29080, e52, buf, 29240, e56, buf, 29304, false, false, true);
        final int e58 = ExpansionArithmetic.twoSquare(buf, 12, e3, buf, 29496, false);
        final int e59 = ExpansionArithmetic.twoSquare(buf, 2, e1, buf, 29502, false);
        final int e60 = ExpansionArithmetic.fastExpansionSum(buf, 29496, e58, buf, 29502, e59, buf, 29508, false, false, false);
        final int e61 = ExpansionArithmetic.twoSquare(buf, 142, e14, buf, 29520, false);
        final int e62 = ExpansionArithmetic.fastExpansionSum(buf, 29508, e60, buf, 29520, e61, buf, 29526, false, false, true);
        final int e63 = ExpansionArithmetic.expansionTimes(buf, 29304, e57, buf, 29526, e62, buf, 29544, true);
        final int e64 = ExpansionArithmetic.fastExpansionSum(buf, 15128, e49, buf, 29544, e63, buf, 36456, false, false, true);
        final int e65 = ExpansionArithmetic.expansionTimes(buf, 352, e19, buf, 654, e28, buf, 57192, true);
        final int e66 = ExpansionArithmetic.expansionTimes(buf, 7896, e40, buf, 40, e7, buf, 57256, true);
        final int e67 = ExpansionArithmetic.fastExpansionSum(buf, 57192, e65, buf, 57256, e66, buf, 57320, false, true, true);
        final int e68 = ExpansionArithmetic.expansionTimes(buf, 29224, e55, buf, 142, e14, buf, 57448, true);
        final int e69 = ExpansionArithmetic.fastExpansionSum(buf, 57320, e67, buf, 57448, e68, buf, 57512, false, false, true);
        final int e70 = ExpansionArithmetic.twoSquare(buf, 0, e0, buf, 57704, false);
        final int e71 = ExpansionArithmetic.twoSquare(buf, 14, e4, buf, 57710, false);
        final int e72 = ExpansionArithmetic.fastExpansionSum(buf, 57704, e70, buf, 57710, e71, buf, 57716, false, false, false);
        final int e73 = ExpansionArithmetic.twoSquare(buf, 368, e20, buf, 57728, false);
        final int e74 = ExpansionArithmetic.fastExpansionSum(buf, 57716, e72, buf, 57728, e73, buf, 57734, false, false, true);
        final int e75 = ExpansionArithmetic.expansionTimes(buf, 57512, e69, buf, 57734, e74, buf, 57752, true);
        final int e76 = ExpansionArithmetic.fastExpansionSum(buf, 36456, e64, buf, 57752, e75, buf, 64664, false, true, true);
        return ExpansionArithmetic.signOf(buf, 64664, e76);
    }
}
